<a href="https://colab.research.google.com/github/jnctproject/pytorch-tutorial/blob/main/introduction_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch

In [3]:
num=[[1,2,3,4],[5,6,7,8]]
num

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
import numpy as np
np1=np.random.rand(2,3,4)
print(np1)
np1.dtype


[[[0.70531176 0.40153133 0.87249702 0.65140318]
  [0.79314474 0.17416709 0.0256722  0.58922013]
  [0.38977658 0.57350804 0.56874678 0.72956139]]

 [[0.00685307 0.51200319 0.2665167  0.53215827]
  [0.79775512 0.56057841 0.66681716 0.42823953]
  [0.94842264 0.83313261 0.77665675 0.48722479]]]


dtype('float64')

In [13]:
tensor_2d=torch.rand(2,3,4)
tensor_2d

tensor([[[0.1490, 0.3593, 0.2535, 0.0642],
         [0.3213, 0.2426, 0.0144, 0.6011],
         [0.0213, 0.5752, 0.4921, 0.2895]],

        [[0.6427, 0.9734, 0.3088, 0.4435],
         [0.2693, 0.3638, 0.3178, 0.7222],
         [0.3399, 0.7269, 0.9737, 0.3921]]])

In [19]:
tensor1=torch.tensor(np1)
tensor1

tensor([[[0.7053, 0.4015, 0.8725, 0.6514],
         [0.7931, 0.1742, 0.0257, 0.5892],
         [0.3898, 0.5735, 0.5687, 0.7296]],

        [[0.0069, 0.5120, 0.2665, 0.5322],
         [0.7978, 0.5606, 0.6668, 0.4282],
         [0.9484, 0.8331, 0.7767, 0.4872]]], dtype=torch.float64)